### ISSUE TITLE
How to view cloud controller,health manager and other component log admin ui

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-community/admin-ui-v1#2]
Hello everyone,

Currently I am able to view only admin_ui log.How to see logs of other component.I have following setting. Earlier I was under assumption that i can see all the logs by specifying path in attribute "log_files",I was wrong
log_file_sftp_keys: []
log_files: [/var/vcap/sys/log/cloud_controller_ng/*.log,/var/vcap/sys/log/admin_ui/admin_ui.log]

From doc I understand that it can show only those logs,that are local to vm where admin_ui is deployed.In the following link they are able to see all logs,seems they are copying the logs to one admin_ui machine.
http://www.slideshare.net/platformcf/the-ibm-dashboard-for-operational-metrics
Is there any way to view other logs also.Is copying logs from other vm to admin_ui vm is the option.
Please guide me on this.

**Comment by rboykin** [comment]
This cannot be done with this old version of the admin ui.  You instead need to be using the version of the admin ui found within the cloudfoundry-incubator:  https://github.com/cloudfoundry-incubator/admin-ui
