### ISSUE TITLE
Problem with accessing admin-ui

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-community/admin-ui-v1#3]
Hi

I installed the admin-ui. In configuration file we mentioned  "cloud_controller_uri: https://api.xxxx.com"
While accessing that from browser, we are getting error saying unable to fetch from https://api.xxxx.com/v2/info

While checking logs i found that its redirecting to our sso page and unable to do that.

> E, [2017-04-25T13:32:34.656110 #13633] ERROR -- : [ -- ] : [ -- ] : Error during redirect_to_login: >#RuntimeError: Unable to fetch from hhttps://api.xxxx.com/v2/info>
> E, [2017-04-25T13:32:34.656294 #13633] ERROR -- : [ -- ] : [ -- ] : /home/ubuntu/admin-ui/lib/admin/cc_rest_client.rb:182:in `rescue in info'
> /home/ubuntu/admin-ui/lib/admin/cc_rest_client.rb:177:in `info'
> /home/ubuntu/admin-ui/lib/admin/cc_rest_client.rb:96:in `sso_login_redirect'
> /home/ubuntu/admin-ui/lib/admin/login.rb:20:in `login_redirect_uri'
> /home/ubuntu/admin-ui/lib/admin/web.rb:2102:in `redirect_to_login'
> /home/ubuntu/admin-ui/lib/admin/web.rb:49:in `block in <class:Web>'

Please help us how to achieve this

**Comment by rboykin** [comment]
@Akhilesh-Anb What version of cloudfoundry are you running?  This repository is very old.  Last commit in Sept 2013.  You should instead be using https://github.com/cloudfoundry-incubator/admin-ui

**Comment by Akhilesh-Anb** [comment]
Hi Rboykin,

I followed the same link what you have mentioned. Can you help me how to get rid of this problem.
When it is trying to that link and redirecting to login page of SSO. How to mention those credentails in 
"cloud_controller_uri:"

**Comment by rboykin** [comment]
@Akhilesh-Anb Please open a new issue on https://github.com/cloudfoundry-incubator/admin-ui and I will answer there
